#!/bin/bash
#!/bin/bash
"Hello, World" >> 0-hello_world

:wq
echo Hello, World
Hello, World
#!/bin/bash
Hello, World
#!/bin/bash
echo "Hello, World"
#!/bin/bash
echo "Hello, World"
#!/bin/bash
echo "Hello, World"
